- name: conditions
  hosts: web
  tasks:
  - name: check expense user is present or not
    ansible.builtin.command: id expense
    register: output
    ignore_errors: true
  
  - name: print output
    ansible.builtin.debug:
      msg: "Output is {{ output }}"

  - name: create user if not exists
    ansible.builtin.command: useradd expense
    when: output.rc != 0
    