- name: filters
  hosts: localhost
  vars:
    COURSE: DevOps
    my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
    my_dict: # this is called as dictionary or map or key/value pairs.
      Course: Ansbile
      Trainer: Sivakumar
      Duration: 120hr  
  vars_prompt:
  - name: number
    prompt: Enter a number
    private: false
  tasks:
  - name: conversion to upper case
    ansible.builtin.debug:
      msg: "I am learning {{COURSE | upper}}"

  - name: conversion to lower case
    ansible.builtin.debug:
      msg: "I am learning {{COURSE | lower}}"

  - name: remove duplicates
    vars:
      NUMBERS: [1,3,5,2,3,4,6,5,6]
    ansible.builtin.debug:
      msg: "Unique list: {{NUMBERS | unique}}"
  
  - name: check given number is less than 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number | int < 10

  - name: check given number is greater than 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is greater than or equal to 10"
    when: number | int >= 10

  - name: Print default
    ansible.builtin.debug:
      msg: "Hi {{Name | default('Dhatri') }}"

  - name: print min and max
    vars:
      ages: [25, 35, 67, 89]
    ansible.builtin.debug:
      msg: " min age: {{ ages | min }}, max age: {{ ages | max }}"

  - name: convert dictionary into items/list
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"

  - name: convert dictionary into items/list
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"

  - name: convert items to dictionary
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  
  - name: convert items to dictionary
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"
  