- name: Vars from promt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: "Please enter username"
    private: false
  - name: PASSWORD
    prompt: "Please enter password"
    private: true
  tasks:
  - name: vars from prompt
    ansible.builtin.debug:
      msg: "Entered Username is {{USERNAME}} and password is {{PASSWORD}}"
